
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jztspixpoxiccvhmajiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dHNwaXhwb3hpY2N2aG1hamlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTcwNTksImV4cCI6MjA1OTE3MzA1OX0.CJnQ9nHNtU_MO2JZKOdoc1pnTR_5ZuTIUGrIIdRgjbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
